In [ ]:
# importing TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#creating tensor with tf.constant()
scalar= tf.constant(7)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check the dimensions of thwe tensor
scalar.ndim

0

In [ ]:
#create a tensor of single dimension
vector = tf.constant([2,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
#creating a 2-D tensor
matrix= tf.constant([[10,10],[2,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [ 2,  7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix with specific dtype
another_matrix= tf.constant([[10. ,8.],
                             [5.,6.],
                             [8.,3.]], dtype= tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  8.],
       [ 5.,  6.],
       [ 8.,  3.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#creating a tensor
tensor= tf.constant([[[2,9,5],
                      [5,6,10]],
                     [[10,4,1],
                      [5,7,8]],
                     [[45,6,7,],
                      [3,4,7]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 2,  9,  5],
        [ 5,  6, 10]],

       [[10,  4,  1],
        [ 5,  7,  8]],

       [[45,  6,  7],
        [ 3,  4,  7]]], dtype=int32)>

In [ ]:
tensor.ndim

3

what have we created so far:
* scalar: a single value
* vector: a number with directions (speed and magnitude)
* tensor: a n-dimensional arr


### Creating Tensors with tf.variable()

In [ ]:
#creating tensors with tf.variable()
tensor1= tf.Variable([10,7])
tensor2=tf.constant([6,9])
tensor1 ,tensor2

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([6, 9], dtype=int32)>)

In [ ]:
#making changes to the tensors
tensor1[0].assign(8)
tensor1
# tensor2[0].assign(4)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 7], dtype=int32)>

### Creating Random Tensors
tensors of some arbitrary size with random numbers as inputs

In [ ]:
#creating random(but the same) tensors

random1= tf.random.Generator.from_seed(42)
random1= random1.normal(shape=(3,2))
random2= tf.random.Generator.from_seed(42)
random2= random2.normal(shape=(3,2))
random1, random2,  random1==random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [ ]:
#shuffle a tensor

not_shuffled= tf.constant([[10,7],
                          [2,4],
                          [5,3]])
shuffled= tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 5,  3],
       [10,  7]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  4],
       [ 5,  3]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed= 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  4],
       [ 5,  3]], dtype=int32)>

In [ ]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)


In [ ]:
print(tf.random.uniform([1]))  # generates 'A3'
print(tf.random.uniform([1]))  # generates 'A4'

tf.Tensor([0.7413678], shape=(1,), dtype=float32)
tf.Tensor([0.7402308], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


### Other ways to create tensors (using NumPy)

In [ ]:
# creating tensors of all ones
tf.ones([4,5], tf.int32)

<tf.Tensor: shape=(4, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)>

In [ ]:
# tensors of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#creating tensors from numpy
import numpy as np
numpy_A= np.arange(1,25, dtype= np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
tf.constant(numpy_A)

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B= tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
B.ndim, A.ndim

(1, 3)

### Getting more info from tensors
  keep in mind the following attributes:
* shape
* rank
* axis or dimension
* size


In [ ]:
#creating a tensor for rank = 4
rank4_tensor= tf.zeros([2,3,4,5])
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
print("Datatype of the tensor: ", rank4_tensor.dtype)
print("Dimension (rank) of the tensor: ", rank4_tensor.ndim )
print("Shape of the tensor: ", rank4_tensor.shape)
print("elements along the 0 axis: ", rank4_tensor.shape[0])
print("elements along the last axis: ", rank4_tensor.shape[-1])
print("size of the tensor: ", tf.size(rank4_tensor).numpy())

Datatype of the tensor:  <dtype: 'float32'>
Dimension (rank) of the tensor:  4
Shape of the tensor:  (2, 3, 4, 5)
elements along the 0 axis:  2
elements along the last axis:  5
size of the tensor:  120


### Indexing and expanding tensors

In [ ]:
# get first two elements of each dimension
rank4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get first element from each dimension for each index except for the final one
rank4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor
rank_2_tensor= tf.constant([[2, 3],
                            [10, 7]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  3],
       [10,  7]], dtype=int32)>

In [ ]:
rank_2_tensor.shape , rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
#display the last item for each of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>

In [ ]:
#add extra dimension i.e expanding our tensor
rank_3_tensor= rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[ 2],
        [ 3]],

       [[10],
        [ 7]]], dtype=int32)>

In [ ]:
#alternative method for tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) #adds an extra dimension at the end
tf.expand_dims(rank_2_tensor, axis=0)  #adds extra dimension at 0 axis
tf.expand_dims(rank_2_tensor, axis=1)  # adds extra dimension at first axis


<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[ 2,  3]],

       [[10,  7]]], dtype=int32)>

### Manipulating Tensors (Tensor Operations)
**Basic Operations**

In [ ]:
tensor= tf.constant([[10,7],
                     [3,4]], dtype= tf.float32)
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[20., 17.],
       [13., 14.]], dtype=float32)>

In [ ]:
tf.multiply(tensor,3)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[30., 21.],
       [ 9., 12.]], dtype=float32)>

In [ ]:
tf.math.pow(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[100.,  49.],
       [  9.,  16.]], dtype=float32)>

In [ ]:
tf.math.floor(tensor,)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  4.]], dtype=float32)>

In [ ]:
tf.math.ceil(tensor)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  4.]], dtype=float32)>

### Matrix Multiplication
in machine learning, matrix multiplication is one of the most common operations

In [ ]:
#matrix multiplication
matrix_A= tf.constant([10,1,4,5], shape=(2,2))
matrix_B= tf.constant([5,6,7,8,10,4], shape=(2,3))
matrix_A, matrix_B


(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  1],
        [ 4,  5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 5,  6,  7],
        [ 8, 10,  4]], dtype=int32)>)

In [ ]:
matrix_C= tf.linalg.matmul(matrix_A,matrix_B)
matrix_C

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[58, 70, 74],
       [60, 74, 48]], dtype=int32)>

In [ ]:
# Matrix Multiplication wiht Python Operator '@'
matrix_C= matrix_A @ matrix_B
matrix_C

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[58, 70, 74],
       [60, 74, 48]], dtype=int32)>

In [ ]:
matrix_A.shape, matrix_B.shape, matrix_C.shape

(TensorShape([2, 2]), TensorShape([2, 3]), TensorShape([2, 3]))

In [ ]:
#transpose of the matrix
matrix_A, tf.transpose(matrix_A)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  1],
        [ 4,  5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  4],
        [ 1,  5]], dtype=int32)>)

In [ ]:
tf.matmul(tf.transpose(matrix_A),matrix_B)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 82, 100,  86],
       [ 45,  56,  27]], dtype=int32)>

### matrix multiplication can be performed:
* tf.matmul()
* tf.tensordot()

In [ ]:
X= tf.constant([1,2,3,6,7,9], shape=(3,2))
Y= tf.constant([10,4,5,7,2,3], shape=(3,2))
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 6],
        [7, 9]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  4],
        [ 5,  7],
        [ 2,  3]], dtype=int32)>)

In [ ]:
#Performing dot product on X and Y (X or Y needs to be transposed)

tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[39, 46],
       [68, 77]], dtype=int32)>

In [ ]:
#tanspose of Y
tf.tensordot(X, tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 18,  19,   8],
       [ 54,  57,  24],
       [106,  98,  41]], dtype=int32)>

In [ ]:
#reshaping Y
tf.matmul(X, tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 24,   8,  11],
       [ 72,  24,  33],
       [133,  46,  62]], dtype=int32)>

In [ ]:
print("original matrix Y:")
print(Y, "\n")
print("reshaped Y into (2,3):")
print(tf.reshape(Y, shape=(2,3)))
print("\n")
print("Transpose of Y:")
print(tf.transpose(Y))


original matrix Y:
tf.Tensor(
[[10  4]
 [ 5  7]
 [ 2  3]], shape=(3, 2), dtype=int32) 

reshaped Y into (2,3):
tf.Tensor(
[[10  4  5]
 [ 7  2  3]], shape=(2, 3), dtype=int32)


Transpose of Y:
tf.Tensor(
[[10  5  2]
 [ 4  7  3]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 18,  19,   8],
       [ 54,  57,  24],
       [106,  98,  41]], dtype=int32)>

### Changing the datatype of a tensor

In [ ]:
# create a tensor of datatype float32
A= tf.constant([1.7, 3.4])
A.dtype, A

(tf.float32,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 3.4], dtype=float32)>)

In [ ]:
#to change float32 to float16 (reduced precision)
D = tf.cast(A, dtype= tf.float16)
D.dtype, D

(tf.float16,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 3.4], dtype=float16)>)

In [ ]:
E= tf.cast(D, dtype= tf.int32)
E.dtype, E

(tf.int32,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>)

### Aggregating Tensors

In [ ]:
# getting the absolute values
tensor= tf.constant([-9,-2])
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([9, 2], dtype=int32)>

different forms of aggregation
* maximum element
* minimum element
* mean of a tensor
* sum of tensor

In [ ]:

tensor= tf.constant (np.random.randint(0,100, size=50))
tensor


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([94, 80, 50, 98, 69, 93, 38, 51, 53, 36, 34, 17, 53, 18, 23,  8, 78,
       20, 16, 83, 97, 20, 42, 75, 20, 88, 12, 17, 25, 83, 11, 83, 11, 15,
       44, 76, 39, 45, 21, 74, 57, 92, 75, 86, 35, 58, 11, 79, 41, 66])>

In [ ]:
# min element in a tensor
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=8>

In [ ]:
#max element
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
# mean
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
#sum
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2510>

In [ ]:
# for variance and std deviation, input must be of complex64 or complex128 type
D= tf.constant(np.random.randint(0,100, size=50), dtype= tf.complex64)
D

<tf.Tensor: shape=(50,), dtype=complex64, numpy=
array([54.+0.j, 68.+0.j, 85.+0.j, 27.+0.j, 42.+0.j, 83.+0.j, 82.+0.j,
       87.+0.j, 61.+0.j,  9.+0.j, 42.+0.j, 37.+0.j,  7.+0.j, 74.+0.j,
       12.+0.j, 50.+0.j, 22.+0.j, 93.+0.j, 81.+0.j, 99.+0.j, 23.+0.j,
        1.+0.j, 78.+0.j, 20.+0.j, 55.+0.j, 80.+0.j, 18.+0.j, 42.+0.j,
       55.+0.j, 43.+0.j,  2.+0.j, 87.+0.j, 36.+0.j, 99.+0.j,  5.+0.j,
       93.+0.j, 42.+0.j, 70.+0.j, 86.+0.j, 90.+0.j, 18.+0.j, 79.+0.j,
       51.+0.j, 19.+0.j, 93.+0.j, 80.+0.j, 62.+0.j, 49.+0.j, 34.+0.j,
       81.+0.j], dtype=complex64)>

In [ ]:
#variance
tf.math.reduce_variance(D)

<tf.Tensor: shape=(), dtype=float32, numpy=880.6655>

In [ ]:
#standard deviation
tf.math.reduce_std(D)

<tf.Tensor: shape=(), dtype=float32, numpy=29.67601>

In [ ]:
import tensorflow_probability as tfp

In [ ]:
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=824>

### Positional maximum and minimum

In [ ]:
# create a tensor
tf.random.set_seed(42)
F= tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#maximum positional element
tf.argmax(F), F[tf.argmax(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [ ]:
#minimum positional element
tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a tensor

In [ ]:
#create a tensor
tf.random.set_seed(42)
G= tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed= tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding in Tensors

In [ ]:
#create a list
lst= [0,1,2,3]
tf.one_hot(lst, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Neural Network Regression with TensorFlow